sudo: required

services:
  - docker

before_install:
  - docker build -t tpwebcp .
  - docker run -d --restart=always -p 2222:22 -p 80:80 -p 8083:8083 -p 3306:3306 -p 443:443 -p 25:25 -p 993:993 -p 110:110 -p 53:53 -p 54:54 -v vesta-data:/vesta tpwebcp
#  - docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
  - docker ps -a
#  - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

#script:
#  - bundle exec rake test