dist: trusty
sudo: required

before_install:
 - apt-get update -y --fix-missing
 - apt-get install -y wget lsb-release
 - /vesta/install/vst-install-ubuntu-local.sh --nginx yes --apache yes --phpfpm no --named yes --remi yes --vsftpd no --proftpd no --iptables no --fail2ban no --quota no --exim yes --dovecot yes --spamassassin no --clamav no --mysql yes --postgresql no --hostname example.com --email test@example.com --password admin -y no

script:
  - /usr/local/vesta/test/test_actions.sh
  - /usr/local/vesta/test/test_json_listing.sh