dist: trusty
sudo: true

addons:
  apt:
    packages:
    - sshpass
    
env:
  global:
#    - secure: "KQcNbJ/l05/JRFz2dUGsvFrKVBqJHH7p5vUV6IZcATmEpC9gb8rBkcP7bFoHDHBwAAXIfvgU1YuhrF0w+kf24A3J/ZiLZ+2IqFXT+ccCKQOBPJMelYGY7gruXdagTX1U13wBx1V1Pz+V0JILXJIJ9FJ8RWzVm245q3caCVnhT3Mtf8L1FPblA9AcChXEwBnWoR7bWm4qzTb5hziOFmvZtadCz3OECQysNTE/lUQBMJUzAMNfOpXFHcTFp/s2baTrimVw7LmzpqsL7uqt4Iw0GUgpXmBGgUPK5lEjUO/luGV/Q/8TVz+iQXnaJM/D24pttiALDJYASmg7EIQx78nGkNWkFFAXHyfs40dvqaBwdVyPgC+4xCJW1mEuJesTJg0rkgXwU+sGuf4xwmSkXGFHlAxGeWgPWTdGO+M1aCu15CAesRrFjW2Q4A4sK2xKBsPLp3MAfscAqFUm/LjwXqs9wMYaBh9gfiTtYnWZoIzk3A0Ol0Zz6JQnXkWicrsIO9x6BwNg7G/RzBpdeX77ezDZrhhqACY2Jx5lPtJEysH8OcQpJtRwjNA1XUFCltcfSViqt5pN+81oHLdv4SKWt07lOLkQXrm9d5XFp21gWIiKyTHGETiMUs0naUVlI3cg9rvwX6seT+VGfBv64UzFnwZsrYgb2sHRbtSVqj/QHbYXV+0="
    - secure: "sA7Nm2RwYyUwkeee6zO4ZSyIi2x90IdrMW104xBi74J2WX2GNuEVZ4Mki17PVFcchuwab4fuNP9DR2ieFn02j6pouhuuSziodLS5qsyPHcwe88nCCVVeQaGAR9Y7xE/XP6J22z/FHj2H730SotQe2HN5zNwcEAtAGsMgcH1Qq21/flhBvW1+t/GEJK4fzKs53z1jsQ0xMTgzpiQZUc3Fdsoed/vcs23QBsN/gz96293dIMDvRgUNfmHebhjc0GkG9mGFj+d+PjQhelTOyuShQdMO9GTEdcDsGWWEeLFl/kLJPD3z8ARUOs+55NRI4bmDLRG/tSFDSf7ke8EhhIVRGeM2E5bj5sfcy4EeJ8LtSO2UE7OR3+EyI3IEpmCyiUUnnmVpAqqWG8XGEyPk0GG0UNnPRJkzq51LQSMutHG/4yW1Oz1DPmsKFF+fyhOZQlyf8KlijVlwD1d5i98K53cmSBmvvR5AWZHvaI28nxTdPluHMXgrv47V9CrdHvwdX4ZR6O3KRW5aCi71cqPN9DU57EgEPasU76c5+rAbgJyiMCinpNp1TG4tHftSALdmZDGPTtx60rYm0dM5qsq/rnxIVzM77nGNJBfeFY0WT2Bl3XcT1vCsbBlSe1nylARNw+Q1ymAxZt0WzOB+ystSoyXRnOGtBCWVYkRozofhk6PVatQ="
  matrix:
    - OS=ubuntu-14-04-x64


#before_install:
#  - test/setup-server.sh $TOKEN $OS
 
script:
  - ls -la
  - test/setup-server.sh $API_TOKEN $OS
  
#  after_script:
#  - echo "Delete droplet"