dist: trusty
sudo: false

services:
  - docker

before_install:
  - docker build -t tpwebcp .
  - docker run -d tpwebcp --name tpwebcp --cap-add=NET_ADMIN /bin/bash -c "/vesta/docker/startup.sh;"
  - docker ps
 
script:
  - docker exec tpwebcp /bin/bash -c "sudo su -; /usr/local/vesta/test/test_actions.sh; (exit \$?)"
  - docker exec tpwebcp /bin/bash -c "sudo su -; /usr/local/vesta/test/test_json_listing.sh; (exit \$?)"